tags:
  - highway:
    - motorway
    - trunk
    - primary
    - secondary
    - tertiary
    - unclassified
    - residential
    - motorway_link
    - trunk_link
    - primary_link
    - secondary_link
    - tertiary_link
    - living_street
    - service
    - pedestrian
    - track
    - bus_guideway
    - escape
    - raceway
    - road
    - busway
    - footway
    - bridleway
    - steps
    - corridor
    - path
    - bus_stop
    - crossing
    - elevator
    - emergency_bay
    - emergency_access_point
    - give_way
    - construction

  - construction
  - footway:
    - sidewalk
    - crossing

  - sidewalk:
    - both
    - left
    - right
    - no

  - sidewalk:both:surface
  - sidewalk:right:surface
  - sidewalk:left:surface
  - sidewalk:both:smoothness
  - sidewalk:left:smoothness
  - sidewalk:right:smoothness
  - sidewalk:both:width
  - sidewalk:right:width
  - sidewalk:left:width
  - sidewalk:both:est_width
  - sidewalk:right:est_width
  - sidewalk:left:est_width
  - sidewalk:both:bicycle
  - sidewalk:right:bicycle
  - sidewalk:left:bicycle
  - sidewalk:both:incline
  - sidewalk:right:incline
  - sidewalk:left:incline
  - sidewalk:both:kerb
  - sidewalk:right:kerb
  - sidewalk:left:kerb
  - sidewalk:both:wheelchair
  - sidewalk:right:wheelchair
  - sidewalk:left:wheelchair
  - sidewalk:both:tactile_paving
  - sidewalk:right:tactile_paving
  - sidewalk:left:tactile_paving
  - sidewalk:both:traffic_sign
  - sidewalk:right:traffic_sign
  - sidewalk:left:traffic_sign

  - est_width
  - segregated
    - yes
    - no

  - cycleway
  - cycleway:
    - lane
    - opposite
    - opposite_lane
    - track
    - opposite_track
    - share_busway
    - opposite_share_busway
    - shared_lane

  - lanes:psv
  - lanes:backward
  - lanes:forward

  - busway:
    - lane
  - bus_bay:
    - both
    - left
    - right

  - parking:left
  - parking:right
  - parking:both
  - parking:
    - surface
    - underground
    - multi-storey
    - rooftop
    - carports
    - garage_boxes
    - sheds
    - StreetParking
    - lane
    - street_side
    - on_kerb
    - half_on_kerb
    - shoulder
    - layby
  - shoulder
    - yes
    - no
    - left
    - right
    - both
  - shoulder:width
  - shoulder:left:width
  - shoulder:right:width
  - shoulder:surface
  - shoulder:left:surface
  - shoulder:right:surface
  - shoulder:bicycle
  - shoulder:left:bicycle
  - shoulder:right:bicycle
  - shoulder:smoothness
  - shoulder:left:smoothness
  - shoulder:right:smoothness
  - shoulder:line
  - shoulder:left:line
  - shoulder:right:line

  - parking:sideorientation:
    - parallel
    - diagonal
    - perpendicular
  - proposed

  - abutters:
    - commercial
    - industrial
    - mixed
    - residential
    - retailetc.

  - bicycle_road:
    - yes
  - bicycle
  - oneway:bicycle


  - change:
    - yes
    - no
    - not_right
    - not_left
    - only_right
    - only_left
  - embankment:
    - yes
    - dyke
  - destination
    - yes
  - ice_road:
    - yes
  - incline
  - junction:
    - roundabout
  - lanes
  - lit:
    - yes
    - no
  - maxspeed
  - motorroad:
    - yes
    - no
  - mountain_pass:
    - yes
  - mtb:scale
  - mtb:scale:uphill
  - mtb:scale:imba
  - mtb:description
  - oneway:
    - yes
    - no
    - reversible
  - overtaking:
    - yes
    - no
    - caution
    - both
    - forward
    - backward

  - parking:lane:
    - parallel
    - diagonal
    - perpendicular
    - marked
    - no_parking
    - no_stopping
    - fire_lane.
  - parking:condition:
    - free
    - ticket
    - disc
    - residents
    - customers
    - private

  - passing_places:
    - yes
  - priority:
    - forward
    - backward
  - priority_road:
    - designated
    - yes_unposted
    - end
  - sac_scale:
    - hiking
    - mountain_hiking
    - demanding_mountain_hiking
    - alpine_hiking
    - demanding_alpine_hiking
    - difficult_alpine_hiking
  - service

  - smoothness:
    - excellent
    - good
    - intermediate
    - bad
    - very_bad
    - horrible
    - very_horrible
    - impassable
  - surface:
    - paved
    - unpaved
    - asphalt
    - concrete
    - paving_stones
    - sett
    - cobblestone
    - metal
    - wood
    - compacted
    - fine_gravel
    - gravel
    - pebblestone
    - plastic
    - grass_paver
    - grass
    - dirt
    - earth
    - mud
    - sand
    - ground

  - tactile_paving:
    - yes
    - no
  - tracktype:
    - grade1
    - grade2
    - grade3
    - grade4
    - grade5
  - traffic_calming
  - trail_visibility:
    - excellent
    - good
    - intermediate
    - bad
    - horrible
    - no
  - trailblazed:
    - yes
    - no
    - poles
    - cairns
    - symbols
  - trailblazed:visibility:
    - excellent
    - good
    - intermediate
    - bad
    - horrible
    - no
  - turn:
    - left
    - slight_left
    - through
    - right
    - slight_right
    - merge_to_left
    - merge_to_right
    - reverse
  - width
  - winter_road:
    - yes
  - emergency:
    - phone
  - milestone
  - mini_roundabout
  - motorway_junction
  - passing_place
  - platform
  - rest_area
  - services
  - speed_camera
  - stop
  - street_lamp
  - toll_gantry
  - traffic_mirror
  - traffic_signals
  - trailhead
  - turning_circle
  - turning_loop
  - ref
  - int_ref
  - loc_ref
  - local_ref
  - nat_ref
  - ncn_ref
  - old_ref
  - rcn_ref
  - reg_ref
  - route_ref
  - noref
    - yes
  - bridge:
    - yes
    - aqueduct
    - boardwalk
    - cantilever
    - covered
    - low_water_crossing
    - movable
    - trestle
    - viaduct
  - source
  - crossing:island
  - access:
    - yes
    - no
    - private
    - permissive
    - permit
    - destination
    - delivery
    - customers
    - designated
    - use_sidepath
    - dismount
    - agricultural
    - forestry
    - discouraged
    - variable
    - unknown
  - name
  - name:left
  - name:right
  - int_name
  - loc_name
  - nat_name
  - official_name
  - old_name
  - reg_name
  - short_name
  - sorting_name
  - alt_name
  - noname
  - name:ab
  - name:ace
  - name:ady
  - name:af
  - name:ak
  - name:alt
  - name:am
  - name:an
  - name:ang
  - name:ar
  - name:arc
  - name:as
  - name:aus
  - name:av
  - name:ay
  - name:az
  - name:ba
  - name:be
  - name:bg
  - name:bh
  - name:bi
  - name:bm
  - name:bn
  - name:bo
  - name:br
  - name:bru
  - name:bs
  - name:bug
  - name:ca
  - name:car
  - name:cdo
  - name:ce
  - name:ceb
  - name:ch
  - name:chm
  - name:chr
  - name:chy
  - name:co
  - name:cs
  - name:csb
  - name:cu
  - name:cv
  - name:cy
  - name:da
  - name:de
  - name:dsb
  - name:dv
  - name:dyu
  - name:dz
  - name:ee
  - name:el
  - name:en
  - name:eo
  - name:es
  - name:et
  - name:etymology
  - name:etymology:wikidata
  - name:etymology:wikipedia
  - name:eu
  - name:fa
  - name:ff
  - name:fi
  - name:fo
  - name:fr
  - name:frr
  - name:fur
  - name:fy
  - name:ga
  - name:gcf
  - name:gd
  - name:gem
  - name:gl
  - name:gn
  - name:grc
  - name:gsw
  - name:gu
  - name:gv
  - name:ha
  - name:haw
  - name:hi
  - name:hif
  - name:hop
  - name:hr
  - name:hsb
  - name:ht
  - name:hu
  - name:hy
  - name:ia
  - name:id
  - name:ie
  - name:ig
  - name:ilo
  - name:inh
  - name:io
  - name:is
  - name:it
  - name:iu
  - name:ja
  - name:ja-Latn
  - name:jbo
  - name:jv
  - name:ka
  - name:ka-Latn
  - name:kaa
  - name:kab
  - name:kbd
  - name:kg
  - name:kk
  - name:kl
  - name:km
  - name:kmr
  - name:kn
  - name:ko
  - name:koi
  - name:kr
  - name:krc
  - name:krl
  - name:ks
  - name:ksh
  - name:ku
  - name:kum
  - name:kv
  - name:kw
  - name:ky
  - name:la
  - name:lad
  - name:language
  - name:lb
  - name:lbe
  - name:left
  - name:lez
  - name:lg
  - name:li
  - name:lmo
  - name:ln
  - name:lo
  - name:lrc
  - name:lt
  - name:lv
  - name:mdf
  - name:mg
  - name:mhr
  - name:mi
  - name:min
  - name:mk
  - name:ml
  - name:mn
  - name:mos
  - name:mr
  - name:ms
  - name:mt
  - name:mwl
  - name:my
  - name:myv
  - name:na
  - name:nap
  - name:nb
  - name:ne
  - name:nl
  - name:nn
  - name:no
  - name:nov
  - name:nso
  - name:oc
  - name:om
  - name:or
  - name:pa
  - name:pag
  - name:pap
  - name:pfl
  - name:pih
  - name:pjt
  - name:pl
  - name:pnb
  - name:prefix
  - name:pronunciation
  - name:ps
  - name:pt
  - name:pwn
  - name:qu
  - name:right
  - name:rm
  - name:rn
  - name:ru
  - name:rue
  - name:rw
  - name:sa
  - name:sah
  - name:sc
  - name:scn
  - name:sco
  - name:sd
  - name:se
  - name:sg
  - name:shn
  - name:si
  - name:signed
  - name:sk
  - name:skr
  - name:sl
  - name:sm
  - name:sma
  - name:sn
  - name:so
  - name:sq
  - name:sr
  - name:ss
  - name:st
  - name:su
  - name:sv
  - name:sw
  - name:syc
  - name:szl
  - name:ta
  - name:te
  - name:tet
  - name:tg
  - name:th
  - name:ti
  - name:tk
  - name:tl
  - name:tlh
  - name:tn
  - name:to
  - name:tpi
  - name:tr
  - name:ts
  - name:tt
  - name:tw
  - name:ty
  - name:udm
  - name:ug
  - name:uk
  - name:ur
  - name:uz
  - name:vi
  - name:vi-Hani
  - name:vls
  - name:vo
  - name:wa
  - name:war
  - name:wikipedia
  - name:wo
  - name:xmf
  - name:yi
  - name:yo
  - name:za
  - name:zu
  - foot:
    - yes
    - no
    - designated
    - permissive
    - use_sidepath
    - private
    - destination
  - lane_markings
    - yes
    - no
  - motorcar:
    - yes
    - no
    - designated
    - agricultural
    - private
    - destination
    - forestry
    - permissive
  - motor_vehicle
  - motorcycle
  - mofa
  - vehicle
  - horse
  - layer
  - maxweight
  - flood_prone
  - note
  - material
  - handrail
  - maxspeed:type
  - note
