tags:
  - natural:
    - fell
    - grassland
    - heath
    - moor
    - scrub
    - shrubbery
    - tree
    - tree_row
    - tree_stump
    - tundra
    - wood
    - bay
    - beach
    - blowhole
    - cape
    - coastline
    - crevasse
    - geyser
    - glacier
    - hot_spring
    - isthmus
    - mud
    - peninsula
    - reef
    - shingle
    - shoal
    - spring
    - strait
    - water
    - wetland
    - arch
    - arete
    - bare_rock
    - cave_entrance
    - cliff
    - dune
    - earth_bank
    - fumarole
    - gully
    - hill
    - peak
    - ridge
    - rock
    - saddle
    - sand
    - scree
    - sinkhole
    - stone
    - valley
    - volcano
  - note
  - source