required_tags:
  - name

tags:
  - place:
    - country
    - state
    - region
    - province
    - district
    - county
    - municipality
    - city
    - borough
    - suburb
    - quarter
    - neighbourhood
    - city_block
    - plot
    - town
    - village
    - hamlet
    - isolated_dwelling
    - farm
    - allotments
    - continent
    - archipelago
    - island
    - islet
    - square
    - locality
    - sea
    - ocean
  - population
  - is_in
  - admin_level
  - name
  - source