tags:
  - waterway:
    - river
    - riverbank
    - stream
    - tidal_channel
    - canal
    - pressurised
    - drain
    - ditch
    - fairway
    - fish_pass
    - dock
    - boatyard
    - dam
    - weir
    - waterfall
    - rapids
    - lock_gate
    - sluice_gate
    - turning_point
    - water_point
    - fuel
  - intermittent:
    - yes
  - seasonal:
    - yes
    - spring
    - summer
    - autumn
    - winter
    - wet_season
    - dry_season
  - destination:
    - name
  - lock:
    - yes
  - mooring:
    - yes
    - private
    - no
  - tunnel:
    - culvert
    - flooded
  - bridge:
    - aqueduct
  - ref:fgkz
  - ref:gnbc
  - ref:gnis
  - ref:regine
  - note
  - source