//
// Copyright (c) 2020, 2021, 2022, 2023 Humanitarian OpenStreetMap Team
//
// This file is part of Underpass.
//
//     Underpass is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     Underpass is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

/// \file geospatial.hh
/// \brief Geospatial validation

#ifndef __GEOSPATIAL_HH__
#define __GEOSPATIAL_HH__

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "unconfig.h"
#endif

#include <memory>
#include "osm/osmobjects.hh"
#include "validate.hh"
#include "utils/yaml.hh"

/// \namespace geospatial
namespace geospatial {

/// \class Geospatial
/// \brief This is the plugin class, deprived from the Validate class
class Geospatial
{
public:
    Geospatial();
    ~Geospatial(void) {  };
    static std::shared_ptr<ValidateStatus> checkWay(const osmobjects::OsmWay &way, const std::string &type, yaml::Yaml &tests, std::shared_ptr<ValidateStatus> &status);
private:
    static bool unsquared(const linestring_t &way, double min_angle = 89, double max_angle = 91);
    static bool duplicate(const std::list<std::shared_ptr<osmobjects::OsmWay>> &allways, osmobjects::OsmWay &way);
    static bool overlaps(const std::list<std::shared_ptr<osmobjects::OsmWay>> &allways, osmobjects::OsmWay &way);
};

} // EOF geospatial namespace

#endif  // EOF __GEOSPATIAL_HH__

// Local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
