//
// Copyright (c) 2020, 2021, 2022, 2023 Humanitarian OpenStreetMap Team
//
// This file is part of Underpass.
//
//     Underpass is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     Underpass is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

/// \file geospatial.hh
/// \brief This file implements the data validation used by HOT

#ifndef __GEOSPATIAL_HH__
#define __GEOSPATIAL_HH__

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "unconfig.h"
#endif

#include <string>
#include <vector>
#include <array>
#include <memory>
#include <iostream>

#include <boost/config.hpp>
#include <boost/geometry.hpp>
#include <boost/dll/alias.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/date_time.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/dll/runtime_symbol_info.hpp>
using namespace boost::posix_time;
using namespace boost::gregorian;

#include "utils/yaml.hh"

// MinGW related workaround
#define BOOST_DLL_FORCE_ALIAS_INSTANTIATION

#include "validate.hh"

/// \namespace geospatial
namespace geospatial {

/// \class Geospatial
/// \brief This is the plugin class, deprived from the Validate class
class Geospatial : public Validate
{
public:
    Geospatial(void);
    ~Geospatial(void) {  };

    /// Check a POI for tags. A node that is part of a way shouldn't have any
    /// tags, this is to check actual POIs, like a school.
    std::shared_ptr<ValidateStatus> checkPOI(const osmobjects::OsmNode &node, const std::string &type);

    /// This checks a way. A way should always have some tags. Often a polygon
    /// is a building
    std::shared_ptr<ValidateStatus> checkWay(const osmobjects::OsmWay &way, const std::string &type);

    // Factory method
    static std::shared_ptr<Geospatial> create(void) {
    return std::make_shared<Geospatial>();
    };
private:
    std::map<std::string, std::vector<std::string>> tests;
    bool unsquared(const linestring_t &way, double min_angle = 89, double max_angle = 91);
    bool duplicate(const std::list<std::shared_ptr<osmobjects::OsmWay>> &allways, osmobjects::OsmWay &way);
    bool overlaps(const std::list<std::shared_ptr<osmobjects::OsmWay>> &allways, osmobjects::OsmWay &way);
};

BOOST_DLL_ALIAS(Geospatial::create, create_plugin)

} // EOF geospatial namespace

#endif  // EOF __GEOSPATIAL_HH__

// Local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
