load_lib "dejagnu.exp"

verbose "Testing Underpass!" 2

set current_dir [pwd]


if { [file tail $current_dir] == "libunderpass.all"} {
    set node "."
} else {
    set node "testsuite/libunderpass.all"
}

set tests [glob $node/*-test]

verbose "Running $tests" 2

foreach test $tests {
    # exec ./$test
    # Execute the test case, and analyse the output
    catch [host_execute $test] ne ""
    verbose "$ne"
    # perror "$test had an execution error" 0
}
