#!/bin/sh
#
# Copyright (c) 2020, 2021 Humanitarian OpenStreetMap Team
#
# This file is part of Underpass.
#
#     Underpass is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Underpass is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.

set -e

dbhost="localhost"
dbuser="underpass"
dbpass="galaxy"

if [ "$1" = "configure" ]; then
    echo -n "Database hostname (default ${dbhost}): "
    read htmp
    if test x"${htmp}" != x; then
	dbhost=${htmp}
    fi
    echo -n "Database user name (if needed, default ${dbuser}): "
    read utmp
    if test x"${utmp}" != x; then
	dbuser=${utmp}
    fi

    echo -n "Database passwd (if any needed) ?: "
    read ptmp
    if test x"${ptmp}" != x; then
	dbpass=${ptmp}
    fi

    if test -e /etc/default/underpass; then
	echo -n "Replace current authentication defaults (default yes)? "
	read tmp
	if test x"${tmp}" != x -a x"${tmp}" != x"no"; then
	    echo "PGHOST=${dbhost}" > /etc/default/underpass
	    echo "PGUSER=${dbuser}" >> /etc/default/underpass
	    echo "PGPASSWORD=${dbpass}" >> /etc/default/underpass
	fi
    else
	echo -n "Create authentication defaults (default yes)? "
	read tmp
	if test x"${tmp}" != x -o x"${tmp}" != x"no"; then
	    echo "PGHOST=${dbhost}" > /etc/default/underpass
	    echo "PGUSER=${dbuser}" >> /etc/default/underpass
	    echo "PGPASSWORD=${dbpass}" >> /etc/default/underpass
	fi
    fi

    args=""
    if test x"${dbhost}" -a x"${dbhost}" != x"localhost"; then
	args="${args} --dbserver ${dbhost} "
    fi
    if test x"${dbuser}" -a x"${dbuser}" != x"${USER}"; then
	args="${args} --dbuser ${dbuser} "
    fi
    if test x"${dbpass}"; then
	args="${args} --dbpasswd ${dbpass} "
    fi
    echo -n "Replace current database ? (default no)? "
    read tmp
    if test x"${tmp}" != x -a x"${tmp}" != x"no"; then
	/usr/bin/bash /usr/share/underpass/setupdb.sh ${args}
    fi
fi
