#!/bin/sh

set -e

dbhost="localhost"
dbuser=${USER}
dbpass=""

if [ "$1" = "configure" ]; then
    echo -n "Database hostname (default ${dbhost}): "
    read htmp
    if test x"${htmp}" != x; then
	dbhost=${htmp}
    fi
    echo -n "Database user name (if needed, default ${dbuser}): "
    read utmp
    if test x"${utmp}" != x; then
	dbuser=${utmp}
    fi

    echo -n "Database passwd (if any needed) ?: "
    read ptmp
    if test x"${ptmp}" != x; then
	dbpass=${ptmp}
    fi

    if test -e /etc/default/underpass; then
	echo -n "Replace current authentication defaults (default yes)? "
	read tmp
	if test x"${tmp}" != x -o x"${tmp}" != x"no"; then
	    echo "PGHOST=${dbhost}" > /etc/default/underpass
	    echo "PGUSER=${dbuser}" >> /etc/default/underpass
	    echo "PGPASSWORD=${dbpass}" >> /etc/default/underpass
	fi
    else
	echo "PGHOST=${dbhost}" > /etc/default/underpass
	echo "PGUSER=${dbuser}" >> /etc/default/underpass
	echo "PGPASSWORD=${dbpass}" >> /etc/default/underpass
    fi

    args=""
    if test x"${dbhost}" -a x"${dbhost}" != x"localhost"; then
	args="${args} -h ${dbhost} "
    fi
    if test x"${dbuser}" -a x"${dbuser}" != x"${USER}"; then
	args="${args} -u ${dbuser} "
    fi
    if test x"${dbpass}"; then
	args="${args} -p ${dbpass} "
    fi
    /usr/bin/bash /usr/share/underpass/setupdb.sh ${args}
fi
