//
// Copyright (c) 2023 Humanitarian OpenStreetMap Team
//
// This file is part of Underpass.
//
//     Underpass is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     Underpass is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

#ifndef __GEO_HH__
#define __GEO_HH__

/// \file geo.hh
/// \brief This file has utilities for working with geometries
///

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "unconfig.h"
#endif

/// \namespace geo
namespace geo {

/// \class Geo
/// \brief Utilities for working with geometries
///
class Geo
{
public:
    Geo(void) {};
    static void epsg4326toEpsg3857(double& x, double& y);
    static double calculateAngle(double x1, double y1, double x2, double y2, double x3, double y3);
};

}

#endif  // EOF __GEO_HH__

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:


