//
// Copyright (c) 2020, 2021, 2022 Humanitarian OpenStreetMap Team
//
// This file is part of Underpass.
//
//     Underpass is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     Underpass is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

#ifndef __STATSCONFIG_HH__
#define __STATSCONFIG_HH__

/// \file statsconfig.hh
/// \brief Simple YAML file reader.
///
/// Read in a YAML config file and create a nested data structure so it can be accessed.

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "unconfig.h"
#endif

#include <map>
#include <string>
#include <vector>

/// \namespace statsconfig
namespace statsconfig {

    class StatsConfig {
        public:
            std::string name;
            std::map<std::string, std::vector<std::string>> area;
            std::map<std::string, std::vector<std::string>> poi;
            std::map<std::string, std::vector<std::string>> line;
            StatsConfig(std::string name);
            StatsConfig
            (
                std::string name,
                std::map<std::string, std::vector<std::string>> area,
                std::map<std::string, std::vector<std::string>> poi,
                std::map<std::string, std::vector<std::string>> line
            );
    };

    class StatsConfigFile {
    public:
        static int read_yaml(std::string filename, std::vector<StatsConfig> &statsconfig);
    };

} // EOF statsconfig namespace

#endif  // EOF __STATSCONFIG_HH__

// Local Variables:
// mode: C++
// indent-tabs-mode: t
// End:
