//
// Copyright (c) 2020, 2021, 2022 Humanitarian OpenStreetMap Team
//
// This file is part of Underpass.
//
//     Underpass is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     Underpass is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

#ifndef __DATA_HH__
#define __DATA_HH__

/// \file data.hh
/// \brief This file is used to work with the OSM Stats database
///
/// This manages the OSM Stats schema in a postgres database. This
/// includes querying existing data in the database, as well as
/// updating the database.

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
#include "unconfig.h"
#endif

#include <algorithm>
#include <array>
#include <iostream>
#include <memory>
#include <pqxx/pqxx>
#include <string>
#include <vector>

#include <boost/date_time.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
using namespace boost::posix_time;
using namespace boost::gregorian;

#include "data/pq.hh"
#include "osm/changeset.hh"
#include "osm/osmchange.hh"

// Forward declarations
namespace changeset {
  class ChangeSet;
};
namespace osmchange {
  class OsmChange;
  class ChangeStats;
}; // namespace osmchange

/// \namespace stats
namespace stats {

/// \class QueryStats
/// \brief This handles all direct database access
///
/// This class handles all the queries to the OSM Stats database.
/// This includes querying the database for existing data, as
/// well as updating the data whenh applying a replication file.
class QueryStats : public pq::Pq {
  public:
    QueryStats(void);
    QueryStats(const std::string &dburl);
    /// close the database connection
    ~QueryStats(void){};

    /// Read in a data file of boundaries as a multipolygon
    bool readGeoBoundaries(const std::string &rawfile) { return false; };

    /// Apply a changeset to the database
    bool applyChange(const changeset::ChangeSet &change) const;
    /// Apply change statistics to the database
    bool applyChange(const osmchange::ChangeStats &change) const;
    /// Get the timestamp of the last update in the database
    ptime getLastUpdate(void);

    std::string fixString(std::string text) const;
  private:
    mutable std::mutex changes_write_mutex; ///< Mutex for data acccess when writing
                                            ///< to the database
};

} // namespace stats

#endif // EOF __DATA_HH__

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
