//
// Copyright (c) 2020, 2021 Humanitarian OpenStreetMap Team
//
// This file is part of Underpass.
//
//     Underpass is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     Underpass is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "unconfig.h"
#endif

#include <string>
#include <vector>
#include <array>
#include <memory>
#include <iostream>
#include <pqxx/pqxx>

#include <boost/date_time.hpp>
#include "boost/date_time/posix_time/posix_time.hpp"
using namespace boost::posix_time;
using namespace boost::gregorian;

#include "hottm/tmusers.hh"

namespace tmdb {

TMUser::TMUser(pqxx::result::const_iterator &row)
{
    id = std::stol(pqxx::to_string(row[0]));
    username = pqxx::to_string(row[1]);
    role = std::stoi(pqxx::to_string(row[2]));
    mapping_level = std::stoi(pqxx::to_string(row[3]));
    tasks_mapped = std::stoi(pqxx::to_string(row[4]));
    tasks_validated = std::stoi(pqxx::to_string(row[5]));
    tasks_invalidated = std::stoi(pqxx::to_string(row[6]));
    name = pqxx::to_string(row[7]);
    // ptime date_registered;
    // ptime last_validation_date;
}

} // EOF tmdb namespace
