name: Deps Dockerfile Build and Push

on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu:latest
    # Steps represent a sequence of tasks that will be executed
    # as part of the job
    steps:
    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Pull remote image
      run: docker pull quay.io/hotosm/underpass-build-deps

    - name: Build and tag Dockerfile
      run: cd docker && docker build -t quay.io/hotosm/underpass-build-deps -f underpass.dockerfile .

    # If there are changes to the dockerfile, then a new image will
    # be pushed. Otherwise nothing will happen.
    - name: Push to Quay.io
      run: docker push quay.io/hotosm/underpass-build-deps
